name: Release to Charmhub

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'The channel where the charm is going to be released to'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - candidate
          - beta
          - edge

jobs:
  ci-tests:
    uses: ./.github/workflows/test.yaml

  release-to-charmhub:
    name: Release to CharmHub
    needs:
      - ci-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --channel 3.x/stable --classic

      - name: Build bundle
        run: |
          charmcraft pack
          mv vantage-agent_*.charm vantage-agent.charm

      - name: Create bundle revision
        run: |
          charmcraft upload --name=vantage-agent --release=${{ github.event.inputs.channel }} vantage-agent.charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}